### ISSUE TITLE
GPUImage version

### ISSUE THREAD

**Issue by asherlporetz** [JinweiClarkChao/GuidedFilter#1]
Hi. If this is to be translated to GPUImage filter can you sketch what part of the C++ code becomes the fragment shader. Also can GPUImageBoxBlurFilter be reused for some parts of the code? Thank you.

**Comment by clarkzjw** [comment]
@asherlporetz Hi, thanks for your interest about guided image filter.

First of all, I have no experience about GPU programming. Sorry about that.

I did a litter search on the web, maybe you can checkout about [this](https://github.com/pAIgn10/GuidedFilter) if you are interested about GPU version of guided image filtering.

**Comment by asherlporetz** [comment]
No worries. Thanks for the reply and this repo.
